# Generated by Django 4.0.4 on 2022-05-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acname', models.CharField(max_length=100)),
                ('Acaddress', models.CharField(max_length=100)),
                ('Acno', models.CharField(max_length=100)),
                ('climit', models.CharField(max_length=300)),
                ('alimit', models.CharField(max_length=300)),
                ('Bname', models.CharField(max_length=300)),
                ('cvv', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRegister_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='fraud_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acname', models.CharField(max_length=100)),
                ('Acaddress', models.CharField(max_length=100)),
                ('Acno', models.CharField(max_length=100)),
                ('ftype', models.CharField(max_length=300)),
                ('dt', models.CharField(max_length=300)),
                ('pname', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='product_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('p_desc', models.CharField(max_length=500)),
                ('p_uses', models.CharField(max_length=200)),
                ('c_name', models.CharField(max_length=300)),
                ('p_price', models.CharField(max_length=300)),
                ('topics', models.CharField(max_length=300)),
                ('pcat', models.CharField(max_length=300)),
                ('senderstatus', models.CharField(default='process', max_length=300)),
                ('ratings', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('sanalysis', models.CharField(max_length=300)),
                ('DT', models.CharField(max_length=300)),
                ('sprovider', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='purchase_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=100)),
                ('dt', models.CharField(max_length=300)),
                ('yc', models.CharField(max_length=300)),
                ('pstatus', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='purchaseconfirm_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=100)),
                ('dt', models.CharField(max_length=300)),
                ('daddr', models.CharField(max_length=300)),
                ('dtype', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='recommend_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname1', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=100)),
                ('loc', models.CharField(max_length=100)),
                ('dt', models.CharField(max_length=300)),
                ('usefull', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='review_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('ureview', models.CharField(max_length=100)),
                ('sanalysis', models.CharField(max_length=100)),
                ('dt', models.CharField(max_length=300)),
                ('tname', models.CharField(max_length=300)),
                ('feedback', models.CharField(max_length=300)),
            ],
        ),
    ]
